import { assertScoringInvariants } from '@/lib/report-builder';
import { dualScores, nearMissFor, normalizeScore, verdictFor, WEIGHTS } from '@/lib/scoring';
import type { AnalysisInput, DimensionKey, DimensionScore, MentorReport, ResearchRound } from '@/lib/types';
import type { MentorInferenceProvider } from './types';

type Profile={scores:number[];confidence:number;coverage:number;summary:string;pivot:string;hard:string;user:string;wedge:string};
const profiles:Record<string,Profile>={
  climate:{scores:[3,2,4,6,4,4,5,2,6,3],confidence:58,coverage:50,summary:'The mission is worthwhile, but “AI for climate” is a theme—not yet a product or a demo.',pivot:'For facilities managers at small venues, build a 15-minute energy-waste audit that uses utility data to recommend the three highest-payback actions.',hard:'Climate impact is not a user workflow. Until you choose one person, one decision, and one measurable outcome, there is nothing to build.',user:'Facilities managers at small venues',wedge:'A rapid, action-ranked audit rather than another footprint dashboard.'},
  chain:{scores:[7,7,9,8,8,7,8,5,7,5],confidence:71,coverage:64,summary:'Portable contribution proofs create a strong sponsor-native demo, but reputation becomes dangerous when context is flattened.',pivot:'For open-source maintainers, build a consent-based contribution passport that verifies three GitHub signals onchain and unlocks one concrete contributor perk.',hard:'Reputation is only valuable when someone changes a decision because of it; a profile alone is not a product.',user:'Open-source maintainers and repeat contributors',wedge:'Consent-based, context-specific proof instead of a universal reputation score.'},
  social:{scores:[7,7,7,9,9,9,8,7,6,6],confidence:78,coverage:69,summary:'A sharp creator workflow is highly demoable; the edge depends on turning public signals into one decision, not more analytics.',pivot:'For emerging TikTok creators, build a brief generator that finds three under-served angles in their niche and produces one evidence-linked shoot plan.',hard:'Creators do not need another dashboard. They need one better decision before they hit record.',user:'Emerging TikTok creators posting 3+ times weekly',wedge:'Evidence-linked content gaps converted directly into a shootable brief.'},
  productivity:{scores:[7,8,8,10,11,9,8,6,6,6],confidence:82,coverage:70,summary:'A focused, visual team ritual has real hackathon edge and a credible path to repeat use.',pivot:'For remote product teams, build a 25-minute multiplayer focus sprint where each person commits one task, proves completion, and unblocks a teammate.',hard:'If the product is merely a prettier timer, teams will try it once and return to Slack.',user:'Remote product teams with recurring coordination debt',wedge:'Completion proof and teammate unblocking, not ambient coworking.'},
  fun:{scores:[9,8,11,10,11,10,9,8,8,7],confidence:86,coverage:77,summary:'The absurd interaction is instantly legible, technically contained, and memorable enough to carry a serious utility layer.',pivot:'For hackathon expo visitors, build a theatrical “pitch dealer” that turns any rambling project description into a brutally concise 20-second pitch—live on stage.',hard:'The joke earns attention for ten seconds. The transformation must earn the next fifty.',user:'Hackathon teams minutes away from demoing',wedge:'A live, public before/after performance rather than a private writing assistant.'},
  general:{scores:[6,5,6,8,8,7,6,5,6,4],confidence:64,coverage:55,summary:'There is a buildable core here, but the audience and differentiating workflow are still under-specified.',pivot:'For one clearly named user, build one repeatable workflow that turns a painful input into a measurable outcome in under two minutes.',hard:'The biggest risk is not implementation. It is building a capable system for a problem nobody urgently owns.',user:'A narrowly defined early adopter',wedge:'Depth in one high-friction workflow rather than breadth.'},
};
function key(idea:string){const v=idea.toLowerCase();if(v.includes('climate')||v.includes('carbon'))return'climate';if(v.includes('onchain')||v.includes('blockchain')||v.includes('defi'))return'chain';if(v.includes('tiktok')||v.includes('social'))return'social';if(v.includes('focus')||v.includes('productiv'))return'productivity';if(v.includes('ridiculous')||v.includes('pigeon')||v.includes('pitch dealer'))return'fun';return'general';}
const notes:Record<DimensionKey,string>={'Problem clarity':'The pain is understandable only after narrowing the workflow.','User specificity':'A tighter early adopter definition increases signal quality.','Novelty':'The combination is differentiated when the workflow—not the AI label—is the wedge.','Feasibility':'The target project can be implemented with a narrow workflow and familiar application infrastructure.','Hackathon scope':'One input-to-outcome path fits the weekend; adjacent automation does not.','Demoability':'The before/after can be made obvious inside 60 seconds.','Sponsor fit':'The target hackathon sponsor and track requirements were not verified, so fit cannot be assessed responsibly.','Adoption':'The first-user path needs a concrete channel and repeated trigger.','Impact':'The utility is credible if the proposed behavior actually changes.','Evidence':'Desk research helps, but direct user evidence is still missing.'};

export class DemoInferenceProvider implements MentorInferenceProvider {
  async evaluate(input:AnalysisInput,research:ResearchRound[]):Promise<MentorReport>{
    const p=profiles[key(input.idea)]; const keys=Object.keys(WEIGHTS) as DimensionKey[];
    const dimensions:DimensionScore[]=keys.map((k,i)=>({key:k,score:p.scores[i],max:WEIGHTS[k],note:notes[k]}));
    const score=normalizeScore(dimensions);const dual=dualScores(dimensions);const verdict=verdictFor(score);const near=nearMissFor(score,verdict);
    const report:MentorReport={analysisId:crypto.randomUUID(),mode:'demo',createdAt:new Date().toISOString(),originalIdea:input.idea,score,...dual,confidence:p.confidence,evidenceCoverage:Math.round(dimensions.find(d=>d.key==='Evidence')!.score/WEIGHTS.Evidence*100),risk:score>=80&&p.confidence>=70?'LOW':score>=55?'MEDIUM':'HIGH',verdict,summary:p.summary,dimensions,
      strengths:['The core transformation can be made visible in a short judge demo.','A narrow first workflow can be shipped with familiar web application tools.','The proposed wedge is tied to a user decision rather than a generic technology claim.'],
      weaknesses:['The target user and triggering moment are not specific enough yet.','Adoption claims rely on proxies rather than direct conversations.','The initial idea contains at least two features that do not serve the core demo.'],
      uncertainties:research.at(-1)?.gaps??[],research,
      novelty:{direct:['General-purpose AI copilots','Vertical workflow assistants'],adjacent:['Manual research and spreadsheets','Expert mentoring sessions'],wedge:p.wedge,judgment:'The novelty is credible at the workflow layer, not at the “uses AI” layer.'},
      adoption:{user:p.user,payer:p.user,why:'The target project removes a high-friction decision immediately before a costly action.',first100:`Recruit small cohorts of ${p.user.toLowerCase()} through communities where this problem already occurs, then invite repeat use after the first successful outcome.`},
      feasibility:[`Build the single workflow described in the pivot: ${p.pivot}`,'Use the team’s most familiar frontend and backend tools.','Persist only the state required to complete and demonstrate the target workflow.','Handle the target project’s most likely failure case explicitly.'],
      sponsorFit:[{name:'Hackathon sponsors',fit:'UNKNOWN',reason:'Sponsor and track information could not be verified from the available target-hackathon evidence.'}],
      pivot:p.pivot,mvp:[`One entry point for ${p.user.toLowerCase()}`,`The core workflow: ${p.pivot}`,'One visible result that proves the promised outcome','A reset path for repeating the demo'],doNotBuild:['A broad platform covering adjacent user workflows','Billing, organization administration, or advanced permissions','Integrations that do not change the core target-project outcome','Long-term analytics before the main interaction is validated'],stack:["The team's fastest familiar web application stack",'Lightweight persistence for the target workflow','Realtime or external APIs only where the submitted project requires them'],
      plan:[{time:'0–2h',milestone:'Lock the target user, trigger, and one measurable project outcome.'},{time:'2–8h',milestone:'Build the target project’s end-to-end happy path.'},{time:'8–14h',milestone:'Add only the state and integrations required by that workflow.'},{time:'14–19h',milestone:'Make the project outcome visually undeniable.'},{time:'19–22h',milestone:'Test the critical failure path and rehearse the project demo.'},{time:'22–24h',milestone:'Cut secondary features, fix rough edges, and submit.'}],
      demoPlan:[{time:'0–10s',beat:`Introduce ${p.user.toLowerCase()} and the specific problem.`},{time:'10–20s',beat:'Show the real input or trigger for the submitted project.'},{time:'20–40s',beat:'Demonstrate the project’s core interaction from start to finish.'},{time:'40–55s',beat:'Reveal the visible outcome and compare it with the previous workflow.'},{time:'55–60s',beat:'Explain why the target user would repeat or pay for this result.'}],hardTruth:p.hard,nextValidation:['Interview three people matching the narrow user definition.','Ask for the last time they faced this exact problem.','Test the pivot as a concierge workflow before expanding the build.'],
      nearMiss:near?{...near,moves:[{action:'Name one narrower target user',impact:4},{action:'Cut the MVP to one visible workflow',impact:3},{action:'Add one direct behavior signal',impact:2}]}:undefined};
    assertScoringInvariants(report);return report;
  }
}
