'use client';
import { useRef, useState } from 'react';
import { benchmarkCases, benchmarkSummary } from '@/lib/benchmark';
import type { AnalysisInput, MentorReport, StepState, WorkflowStep } from '@/lib/types';

const examples=[
  {label:'AI CLIMATE APP',idea:'An AI app that helps people reduce their carbon footprint.',tag:'PIVOT'},
  {label:'ONCHAIN REPUTATION',idea:'An onchain reputation system for open-source contributors.',tag:'DOUBLE DOWN'},
  {label:'TIKTOK INTELLIGENCE',idea:'An AI tool that tells TikTok creators what content to make next.',tag:'DOUBLE DOWN'},
  {label:'MULTIPLAYER FOCUS',idea:'A multiplayer focus room where remote teams race to finish one task together.',tag:'NEAR MISS'},
  {label:'RIDICULOUS PITCH DEALER',idea:'A ridiculous live pitch dealer that turns rambling hackathon ideas into a sharp 20-second pitch.',tag:'ALL IN'},
];
const stepLabels=['Reading hackathon','Mapping tracks','Researching landscape','Finding missing evidence','Running follow-up research','Evaluating feasibility','Scoring idea','Designing the pivot','Persisting report'];
const defaultForm:AnalysisInput={hackathonUrl:'https://hackathon.example/ai-build',idea:'',teamSize:3,hours:36,strengths:'TypeScript, product design',goal:'Win sponsor track',simulateFailure:false};

function Meter({label,value,tone='gold'}:{label:string;value:number;tone?:string}){return <div className="meter"><div><span>{label}</span><b>{value}</b></div><div className="meter-track"><i className={tone} style={{width:`${value}%`}}/></div></div>}
function Pill({children}:{children:React.ReactNode}){return <span className="pill">{children}</span>}

export default function PivotApp(){
  const [form,setForm]=useState(defaultForm);const [view,setView]=useState<'home'|'processing'|'report'>('home');const [report,setReport]=useState<MentorReport|null>(null);const [error,setError]=useState('');const [steps,setSteps]=useState<WorkflowStep[]>(stepLabels.map((label,i)=>({id:`step-${i+1}`,label,state:'pending'})));const [mentor,setMentor]=useState(false);const [copied,setCopied]=useState(false);const [sound,setSound]=useState(false);const intakeRef=useRef<HTMLDivElement>(null);
  const canRun=form.idea.trim().length>=12;
  function updateStep(index:number,state:StepState,detail?:string,attempt?:number){setSteps(current=>current.map((s,i)=>i===index?{...s,state,detail,attempt}:s));}
  async function run(){if(!canRun)return;setError('');setReport(null);setView('processing');setSteps(stepLabels.map((label,i)=>({id:`step-${i+1}`,label,state:'pending'})));const key=crypto.randomUUID();
    const request=fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(form)}).then(async r=>{const data=await r.json() as {error?:string;report?:MentorReport};if(!r.ok||!data.report)throw new Error(data.error??'Analysis failed');return data.report;});
    for(let i=0;i<stepLabels.length;i++){updateStep(i,'running');await new Promise(r=>setTimeout(r,i===3||i===4?430:270));if(form.simulateFailure&&i===5){updateStep(i,'failed','HTTP 503 · attempt 1/3',1);await new Promise(r=>setTimeout(r,700));updateStep(i,'retrying','Replaying idempotent evaluation step…',2);await new Promise(r=>setTimeout(r,650));updateStep(i,'recovered','Recovered · no duplicate report created',2);}else updateStep(i,'completed');}
    try{setReport(await request);setView('report');window.scrollTo({top:0,behavior:'smooth'});}catch(e){setError(e instanceof Error?e.message:'Analysis failed');setView('home');setTimeout(()=>intakeRef.current?.scrollIntoView({behavior:'smooth'}),50);}
  }
  async function copy(){if(!report)return;await navigator.clipboard.writeText(`PIVOT! — ${report.verdict}\nPIVOT SCORE ${report.score}/100\n${report.summary}\n\nTHE PIVOT\n${report.pivot}`);setCopied(true);setTimeout(()=>setCopied(false),1800);}
  const active=steps.findIndex(s=>s.state==='running'||s.state==='retrying'||s.state==='failed');
  const completed=steps.filter(s=>['completed','recovered'].includes(s.state)).length;

  if(view==='processing')return <main className="site-shell process-page"><Header sound={sound} setSound={setSound}/><section className="process-wrap">
    <div className="process-kicker">WORKFLOW RUN / {completed+1} OF {steps.length}</div><h1>THE HOUSE IS<br/><em>RUNNING THE NUMBERS.</em></h1><div className="process-layout"><div className="reels" aria-hidden="true"><div>?</div><div>{completed.toString().padStart(2,'0')}</div><div>!</div></div><div className="workflow" aria-live="polite">{steps.map((step,i)=><div className={`workflow-step ${step.state}`} key={step.id}><span className="step-num">{String(i+1).padStart(2,'0')}</span><span className="step-name">{step.label}<small>{step.detail}</small></span><span className="step-state">{step.state==='completed'?'DONE':step.state.toUpperCase()}</span></div>)}</div></div>
    <div className="progress-line"><i style={{width:`${Math.max(4,(completed/steps.length)*100)}%`}}/></div><p className="process-note">{steps[active]?.state==='failed'?'THE HOUSE HIT A FAULT.':'Evidence is being saved between rounds.'} <span>{steps[active]?.state==='retrying'?'Replaying safely—no duplicate bets placed.':'Round 2 is chosen from Round 1 gaps.'}</span></p>
  </section></main>;

  if(view==='report'&&report)return <main className={`site-shell report-page verdict-${report.verdict.toLowerCase().replace(' ','-')}`}><Header sound={sound} setSound={setSound}/><section className="report-hero">
    <div className="report-id">ANALYSIS {report.analysisId.slice(0,8).toUpperCase()} · {report.mode.toUpperCase()} EVIDENCE</div><div className="verdict-grid"><div><p>THE VERDICT</p><h1>{report.verdict}</h1><div className="verdict-summary">{report.summary}</div></div><div className="score-dial"><span>PIVOT SCORE</span><b>{report.score}</b><small>/ 100</small></div></div>
    {report.nearMiss&&<div className="near-miss"><strong>NEAR MISS</strong><span>You are <b>{report.nearMiss.points} points</b> from {report.nearMiss.nextVerdict}.</span>{report.nearMiss.moves.map(m=><em key={m.action}>+{m.impact} {m.action}</em>)}</div>}
    <div className="score-ribbon"><div><small>HACKATHON EDGE</small><b>{report.hackathonEdge}</b></div><div><small>REAL-WORLD EDGE</small><b>{report.realWorldEdge}</b></div><div><small>CONFIDENCE</small><b>{report.confidence}%</b></div><div><small>EVIDENCE COVERAGE</small><b>{report.evidenceCoverage}%</b></div><div><small>RISK</small><b>{report.risk}</b></div></div>
  </section>
  <section className="report-body"><div className="report-main">
    <ReportSection number="01" title="What works" intro="Signals worth keeping"><CardList items={report.strengths} tone="good"/></ReportSection>
    <ReportSection number="02" title="What breaks" intro="Assumptions most likely to cost the weekend"><CardList items={report.weaknesses} tone="bad"/></ReportSection>
    <ReportSection number="03" title="Research trail" intro="Round 2 is derived from gaps found in Round 1">
      <div className="research-trail">{report.research.map((round,idx)=><article className="round" key={round.round}><header><Pill>ROUND {round.round}</Pill><h3>{round.focus}</h3></header><div className="queries">{round.queries.map(q=><span key={q}>↳ {q}</span>)}</div>{round.findings.map(f=><div className="evidence" key={f.id}><div><span className="demo-tag">{f.demo?'DEMO EVIDENCE':'LIVE SOURCE'}</span><b>{f.title}</b><p>{f.summary}</p></div><span className="confidence">{f.confidence}%<small>CONF.</small></span></div>)}<div className="gap"><b>{idx===0?'MISSING SIGNAL':'UNCONFIRMED'}</b>{round.gaps.map(g=><span key={g}>{g}</span>)}</div></article>)}</div>
    </ReportSection>
    <ReportSection number="04" title="The pivot" intro="A stronger version of the bet"><div className="original"><small>ORIGINAL</small>“{report.originalIdea}”</div><div className="pivot-copy"><small>PIVOT</small>{report.pivot}</div></ReportSection>
    <ReportSection number="05" title="MVP & scope" intro="Exactly what ships"><div className="split"><div><h3>MUST BUILD</h3><CardList items={report.mvp} tone="good"/></div><div><h3>DO NOT BUILD</h3><CardList items={report.doNotBuild} tone="bad"/></div></div></ReportSection>
    <ReportSection number="06" title="24-hour plan" intro="A critical path, not a wish list"><div className="timeline">{report.plan.map(p=><div key={p.time}><b>{p.time}</b><span>{p.milestone}</span></div>)}</div></ReportSection>
    <ReportSection number="07" title="60-second demo" intro="Show transformation, not features"><div className="demo-timeline">{report.demoPlan.map(d=><div key={d.time}><b>{d.time}</b><p>{d.beat}</p></div>)}</div></ReportSection>
    {mentor&&<><ReportSection number="08" title="Mentor view" intro="Detailed scoring, feasibility, and sponsor fit"><div className="dimension-grid">{report.dimensions.map(d=><Meter key={d.key} label={`${d.key} · ${d.score}/${d.max}`} value={Math.round(d.score/d.max*100)}/>)}</div><div className="sponsor-list">{report.sponsorFit.map(s=><div key={s.name}><Pill>{s.fit}</Pill><b>{s.name}</b><p>{s.reason}</p></div>)}</div><h3>REAL-WORLD CONSTRAINTS</h3><CardList items={report.feasibility}/></ReportSection><ReportSection number="09" title="Novelty & adoption" intro="Good hackathon idea ≠ good startup idea"><div className="two-col"><div><h3>DIFFERENTIATING WEDGE</h3><p>{report.novelty.wedge}</p><p className="muted">{report.novelty.judgment}</p></div><div><h3>FIRST 100 USERS</h3><p>{report.adoption.first100}</p><p className="muted">User: {report.adoption.user}</p></div></div></ReportSection></>}
    <div className="hard-truth"><small>ONE HARD TRUTH</small><p>“{report.hardTruth}”</p></div>
  </div><aside className="report-aside"><div className="sticky-card"><span className="aside-label">MENTOR CONTROLS</span><button className={mentor?'toggle active':'toggle'} onClick={()=>setMentor(!mentor)}><span/> MENTOR VIEW <b>{mentor?'ON':'OFF'}</b></button><button className="outline-btn" onClick={copy}>{copied?'COPIED ✓':'COPY RESULT'}</button><button className="outline-btn" onClick={()=>{setView('home');setTimeout(()=>intakeRef.current?.scrollIntoView({behavior:'smooth'}),50)}}>DEAL ANOTHER IDEA</button><hr/><h3>RECOMMENDED STACK</h3>{report.stack.map(x=><p key={x}>◆ {x}</p>)}<hr/><h3>NEXT VALIDATION</h3>{report.nextValidation.map((x,i)=><p key={x}>{i+1}. {x}</p>)}</div></aside></section></main>;

  return <main className="site-shell"><Header sound={sound} setSound={setSound}/><section id="top" className="hero"><div className="eyebrow"><span>01</span> HACKATHON IDEA CASINO</div><div className="hero-grid"><div className="hero-copy"><h1>CHECK THE ODDS<br/><em>BEFORE</em> YOU BUILD.</h1><p>PIVOT researches the hackathon, pressure-tests your idea, and tells you which version is actually worth your next 36 hours.</p><button className="text-link" onClick={()=>intakeRef.current?.scrollIntoView({behavior:'smooth'})}>↓ RUN THE ODDS</button><div className="credibility"><span className="mini-chip">♠</span> Built from real hackathon mentoring workflows.</div></div><div className="terminal" ref={intakeRef} aria-label="Idea analysis form"><div className="terminal-head"><span>IDEA INTAKE / 001</span><span className="live-label">● READY</span></div><label htmlFor="hackathon">HACKATHON URL <small>OPTIONAL IN DEMO</small></label><input id="hackathon" type="url" value={form.hackathonUrl} onChange={e=>setForm({...form,hackathonUrl:e.target.value})} placeholder="https://hackathon.devpost.com"/><label htmlFor="idea">YOUR ROUGH IDEA</label><textarea id="idea" value={form.idea} onChange={e=>setForm({...form,idea:e.target.value})} placeholder="An AI app that helps with climate change..." rows={4}/><details><summary>TEAM CONSTRAINTS <span>OPTIONAL +</span></summary><div className="constraint-grid"><label>TEAM SIZE<input type="number" min="1" max="20" value={form.teamSize} onChange={e=>setForm({...form,teamSize:Number(e.target.value)})}/></label><label>HOURS AVAILABLE<input type="number" min="4" max="168" value={form.hours} onChange={e=>setForm({...form,hours:Number(e.target.value)})}/></label><label className="wide">TECHNICAL STRENGTHS<input value={form.strengths} onChange={e=>setForm({...form,strengths:e.target.value})}/></label><label className="wide">GOAL<select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}><option>Win sponsor track</option><option>Build something viral</option><option>Validate startup idea</option><option>Learn a technology</option><option>Build public good</option><option>Ship fastest possible MVP</option></select></label></div></details><label className="failure-toggle"><input type="checkbox" checked={form.simulateFailure} onChange={e=>setForm({...form,simulateFailure:e.target.checked})}/><span/> JUDGE MODE: SIMULATE EVALUATION FAILURE</label><button className="run-button" type="button" disabled={!canRun} onClick={run}><span className="run-icon">◆</span><span><small>PRESS TO ANALYZE</small>RUN THE ODDS</span><span className="arrow">→</span></button>{error&&<p className="form-error">{error}</p>}<p className="microcopy">Serious mentoring. Questionable visual metaphor.</p></div></div></section>
  <section className="signal-strip"><div><b>10</b><span>MENTOR DIMENSIONS</span></div><div><b>2×</b><span>RESEARCH ROUNDS</span></div><div><b>15</b><span>BENCHMARK CASES</span></div><div><b>48h</b><span>BUILD REALITY CHECK</span></div></section>
  <section className="demo-hands"><div className="section-kicker">TRY A DEMO IDEA</div><h2>EVERY IDEA GETS<br/>A DIFFERENT HAND.</h2><div className="hand-grid">{examples.map((x,i)=><button key={x.label} onClick={()=>{setForm({...form,idea:x.idea});intakeRef.current?.scrollIntoView({behavior:'smooth'})}}><span>0{i+1}</span><b>{x.label}</b><small>{x.tag}</small><i>→</i></button>)}</div></section>
  <section id="method" className="method"><div><div className="section-kicker">THE MENTORING ENGINE</div><h2>RESEARCH.<br/>PRESSURE-TEST.<br/><em>SUBTRACT.</em></h2></div><div className="method-steps"><article><span>01</span><h3>READ THE ROOM</h3><p>Map tracks, judging criteria, sponsors, and the ecosystem around the idea.</p></article><article><span>02</span><h3>CHASE THE GAPS</h3><p>Save Round 1, find what is missing, then run a second search shaped by those gaps.</p></article><article><span>03</span><h3>MAKE THE CALL</h3><p>Score hackathon edge and real-world edge separately. Then prescribe the version worth shipping.</p></article></div></section>
  <section id="benchmark" className="benchmark"><div className="section-kicker">MENTOR BENCHMARK / EXPERT-JUDGMENT GROUND TRUTH</div><div className="benchmark-head"><h2>WE MEASURE THE MENTOR,<br/>NOT JUST THE MODEL.</h2><p>This is a directional benchmark, not scientific truth. Fifteen representative ideas are compared against broad expert expectations, including visible misses.</p></div><div className="metric-grid"><div><b>{benchmarkSummary.agreement}%</b><span>VERDICT AGREEMENT</span></div><div><b>{benchmarkSummary.averageDeviation}</b><span>AVG SCORE DEVIATION</span></div><div><b>{(benchmarkSummary.medianMs/1000).toFixed(1)}s</b><span>MEDIAN TASK TIME</span></div><div><b>{benchmarkSummary.schemaSuccess}%</b><span>SCHEMA VALID</span></div></div><div className="benchmark-table"><div className="table-row table-head"><span>CASE</span><span>EXPECTED</span><span>MODEL</span><span>PRIMARY WEAKNESS</span></div>{benchmarkCases.map(c=><div className={`table-row ${c.expected!==c.model?'miss':''}`} key={c.name}><b>{c.name}</b><span>{c.expected}</span><span>{c.model}</span><p>{c.weakness}</p></div>)}</div><p className="cost-note">Estimated live inference cost / evaluation: {benchmarkSummary.estimatedCost}. Varies by model and token use.</p></section><Footer/></main>;
}

function Header({sound,setSound}:{sound:boolean;setSound:(v:boolean)=>void}){return <nav className="topbar" aria-label="Primary navigation"><a className="brand" href="#top"><span className="brand-mark">P!</span><span>PIVOT!</span></a><div className="header-links"><a href="#method">METHOD</a><a href="#benchmark">BENCHMARK</a></div><div className="nav-meta"><span className="status-dot"/><span>DEMO MODE</span><button aria-label={`${sound?'Mute':'Enable'} sounds`} onClick={()=>setSound(!sound)}>{sound?'SOUND ON':'SOUND OFF'}</button></div></nav>}
function ReportSection({number,title,intro,children}:{number:string;title:string;intro:string;children:React.ReactNode}){return <section className="report-section"><header><span>{number}</span><div><h2>{title}</h2><p>{intro}</p></div></header>{children}</section>}
function CardList({items,tone='neutral'}:{items:string[];tone?:string}){return <div className={`card-list ${tone}`}>{items.map((x,i)=><div key={x}><span>{tone==='good'?'+':tone==='bad'?'×':String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div>}
function Footer(){return <footer><div className="brand"><span className="brand-mark">P!</span><span>PIVOT!</span></div><p>Before you spend 36 hours building it, check the odds.</p><span>BUILT FOR HACKERS WHO WOULD RATHER SHIP THE RIGHT THING.</span></footer>}
